# Generated by Django 5.1 on 2024-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_armazenamento', models.DateField(auto_now_add=True)),
                ('hora_armazenamento', models.TimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
