# Generated by Django 4.2.7 on 2024-09-06 14:08

import Agil.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoAGil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('cnae_principal_descricao', models.CharField(max_length=255)),
                ('cnae_principal_codigo', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('data_abertura', models.DateField()),
                ('ddd', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_logradouro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
