# Generated by Django 4.2.7 on 2024-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoAGil', '0002_empresa_email_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
