# Generated by Django 5.0.3 on 2024-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoAGil', '0004_alter_empresa_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_logradouro',
            field=models.CharField(max_length=120),
        ),
    ]
