# Generated by Django 4.2.7 on 2024-09-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancoAGil', '0005_alter_empresa_complemento_alter_empresa_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
    ]
