# Generated by Django 4.2.7 on 2024-09-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancoAGil', '0006_remove_email_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Cpf',
        ),
    ]
